### ISSUE TITLE
Allow for HTTPS

### ISSUE THREAD

**Issue by twistedpolitiks** [SnoringDragon/gluetun-qbittorrent-port-manager#1]
The script is working great. I have switched my qbittorrent over to HTTPS, and notice that your script only supports HTTP at the moment. I'm not terribly good at git or docker, and am fumbling trying to get it so that your container will support HTTPS. If I can figure it out, I'll put in a pull request, but it might be a good idea to do it if you have the time.

**Comment by SnoringDragon** [comment]
I would just like to let you know that this project as well as your fork are likely now redundant as the latest version of gluetun supports `VPN_PORT_FORWARDING_LISTENING_PORT`. As a result, this project is being archived without resolving issues.

**Comment by SnoringDragon** [comment]
This has been added now as of release 1.1

**Comment by twistedpolitiks** [comment]
Thank you for the heads up, I'll definitely take a look at the new option
gluetun has provided us.

**Comment by SnoringDragon** [comment]
> Thank you for the heads up, I'll definitely take a look at the new option gluetun has provided us.

Bit of a correction, the feature exists, but I mistakenly assumed it solved the same problem that this project seeks to, but it does not. 

The implemented solution in gluetun does not account for the fact that qbittorrent includes the config port in its announcements to trackers, which is not corrected by this port remap.

As a result, this project is still necessary for getting those packets right, thus making the port redirection irrelevant for torrent services.
