### ISSUE TITLE
Alpine Based Image

### ISSUE THREAD

**Issue by Stetsed** [SnoringDragon/gluetun-qbittorrent-port-manager#2]
Hey,

I replaced the ubuntu base with an alpine base which takes the image size down to about 7MiB.

```
FROM alpine:latest

RUN apk update && apk add --no-cache curl inotify-tools

WORKDIR /app

ENV QBITTORRENT_SERVER=localhost
ENV QBITTORRENT_PORT=8080
ENV QBITTORRENT_USER=admin
ENV QBITTORRENT_PASS=adminadmin
ENV PORT_FORWARDED=tmp/gluetun/forwarded_port

COPY ./start.sh /app/
RUN chmod 770 /app/start.sh

CMD ["/app/start.sh"]

```

**Comment by Stetsed** [comment]
getting issues don't know why though

**Comment by Stetsed** [comment]
Never mind got it working, was cuz alpine image doesn't come with bash by default, now a 7.5MB file.

```
FROM alpine:latest

RUN apk update && apk add --no-cache curl inotify-tools bash

WORKDIR /app

ENV QBITTORRENT_SERVER=localhost
ENV QBITTORRENT_PORT=8080
ENV QBITTORRENT_USER=admin
ENV QBITTORRENT_PASS=adminadmin
ENV PORT_FORWARDED=tmp/gluetun/forwarded_port

COPY ./start.sh /app/
RUN chmod 770 /app/start.sh

CMD ["/app/start.sh"]
```

**Comment by asininemonkey** [comment]
Might be worth submitting a PR with your Dockerfile changes so this can be reviewed and merged.

**Comment by SnoringDragon** [comment]
I would just like to let you know that this project as well as your fork are likely now redundant as the latest version of gluetun supports `VPN_PORT_FORWARDING_LISTENING_PORT`. As a result, this project is being closed without resolving issues.

**Comment by SnoringDragon** [comment]
Thank you very much for the suggestion. This has been added now as of version 1.2
