### ISSUE TITLE
arm support?

### ISSUE THREAD

**Issue by thejaykid7** [SnoringDragon/gluetun-qbittorrent-port-manager#3]
Hi,

just wondering if its possible to generate cross platform image for folks like myself on arm?

**Comment by SnoringDragon** [comment]
I have added support for all platforms supported by Gluetun (listed below), though I am unable to test them, so please let me know if there are any problems.

linux/386
linux/amd64
linux/arm/v6
linux/arm/v7
linux/arm64
linux/ppc64le
